### ISSUE TITLE
unquote parameters

### ISSUE THREAD

**Issue by virusdefender** [tufanbarisyildirim/gonginx#3]
for example `load_module "modules/ngx_stream_module.so";`

we will get a quoted string now 

```
{
        "Block": null,
        "Name": "load_module",
        "Parameters": [
            "\"modules/ngx_stream_module.so\""
        ]
}
```

**Comment by tufanbarisyildirim** [comment]
@virusdefender  thanks for reporting. You can trim it before using. This needs some more developements to keep parameters with sth like `quoted` flag. Because those are needed to be quoted on dumping. I will think on it to find an easy way without a gib refactor but I would like to keep as is. (if you have any advice, do not hesitate to open a PR)

**Comment by tufanbarisyildirim** [comment]
closing this, I think unfolding should not be a part of parsing.
